---
title: "BRI Emergency Department A300 PodMonitor"
output:
  html_document:
    includes:
      in_header: podMonitor_header.html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(sofa)
library(janitor)
library(jsonlite)
library(glue)
#library(pluralize)
library(htmltools)

SECRET_USR <- Sys.getenv("SECRET_USR")
SECRET_PWD <- Sys.getenv("SECRET_PWD")

paste(SECRET_USR,"\t",SECRET_PWD,"\n")

z<-Cushion$new(
  host='1c326334-de1f-4cd4-8111-f7ae4ef14f49-bluemix.cloudantnosqldb.appdomain.cloud',
  transport='https',
  port=NULL,
  user=SECRET_USR,
  pwd=SECRET_PWD)

res <- db_query(z, dbname = "bri_database",
                selector = list(`_id` = list(`$gt` = NULL)),
                fields = c("_id","eventName", "uniqueID", "date_then", "podWorking", "lastSent", "lastNotSent", "podReported"),
                as = "json")

result<-fromJSON(res)$docs

times<-result%>%
  filter(eventName %in% c("BROKEN","FIXED","REPORTED"))%>%
  mutate(podWorking=if_else(podWorking=="TRUE",TRUE,FALSE))%>%
  mutate(podWorking=lag(podWorking, default =0))%>%
  mutate(order=cumsum(podWorking))%>%
  mutate(timestamp=ymd_hms(`_id`))%>%
  select (timestamp,eventName,order)%>%
  group_by(order)%>%
  pivot_wider(names_from = eventName, values_from = timestamp)%>%
  mutate(downtime=round(time_length(interval(BROKEN,FIXED),"hour"),1))%>%
  mutate(FIXED=replace_na(FIXED,now()))

counts<-result%>%
  filter(eventName %in% c("BROKEN","FIXED"))%>%
  mutate(podWorking=if_else(podWorking=="TRUE",TRUE,FALSE))%>%
  mutate(podWorking=lag(podWorking, default =0))%>%
  mutate(order=cumsum(podWorking))%>%
  select (lastNotSent,eventName,order)%>%
  group_by(order)%>%
  pivot_wider(names_from = eventName, values_from = lastNotSent)%>%
  mutate(notsent=FIXED-(BROKEN-1))%>%
  select(order,notsent)

summaryData<-left_join(times,counts, by="order")%>%
  filter( (downtime>=1) %>% replace_na(TRUE) )

downtime<-summaryData%>%
  mutate(start = ymd_hms(BROKEN),
         end= ymd_hms(FIXED),
         downtime=interval(start,end))%>%
  pull(downtime)

if(tail(result$podWorking,1)){
  podStatus='<span style="color:green; font-weight:bold;">WORKING</span>'
}else{
  podStatus='<span style="color:red; font-weight:bold;">BROKEN</span>'
}

```  

```{r, echo=FALSE}
htmltools::img(src = knitr::image_uri("BRHCLogo.png"), 
               alt = 'BRCH logo', 
               style = 'position:absolute; top:0; left:0; padding:10px; height:100px;')

htmltools::img(src = knitr::image_uri("CED_Rings_Logo.png"), 
               alt = 'CED logo', 
               style = 'position:absolute; top:0; right:0; padding:10px; height:100px;')
```

```{css, echo=FALSE}
#header {
  margin-top: 150px;
}
```

#### Current status as of `r now()`  is: `r podStatus`

```{r createTimeblock}  

oldestDate=dmy('01-11-2023')

timeblock_fast<-data.frame(
  times=seq(ymd_hm(paste0(oldestDate,' 08:00')),now(),by="1 hour"))|>
  mutate(base_date = as.Date(times),
         base_hour=hour(times))%>%
  mutate(census=FALSE)%>%
  mutate(base_date=case_when(base_hour<8 ~ base_date-days(1),
                             TRUE~base_date))%>%
  mutate(weekday=lubridate::wday(base_date,label=TRUE, week_start=1))%>%
  mutate(weekday=factor(as.character(weekday), levels=rev(levels(weekday))))%>%
  mutate(week=floor_date(base_date,unit="week", week_start=1))%>%
  mutate(week=paste("w/c:",(format(week, format="%d %b"))))%>%
  mutate(week=forcats::as_factor(week))%>%
  mutate(base_hour=factor(base_hour, levels=c(8:23,0:7)))%>%
  mutate(status = if_else(times %within% as.list(downtime), FALSE, TRUE))

listOfDates<-c(seq(dmy("01-11-23"),today(),by="1 month"))

startDate=listOfDates
endDate=tail(listOfDates,-1)

startDate=ymd_hm(paste0(startDate,' 08:00'))
endDate=c(ymd_hm(paste0(endDate,' 07:59')),now())

startDate<-rev(startDate)
endDate<-rev(endDate)

testFunc <- function(go,stop) {
  paste0(go,"  ",stop)
}

render_child <- function(startDate, endDate) {
  res = knitr::knit_child(
   text = xfun::read_utf8("podMonitor_child.rmd"),
   envir = rlang::env(startdate = startDate, enddate = endDate),
   quiet = TRUE
  )
  cat(res, sep = '\n')
  cat("\n")
}

```

(last event received: `r ymd_hms(tail(result[1],1))`)

```{r}
#| results: "asis"
#| echo: false
#map2(startDate,endDate,testFunc)
walk2(startDate,endDate,render_child)
```
