on:
  schedule:
    - cron: "*/5 * * * *"
    
jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse
            any::sofa
            any::janitor
            any::jsonlite
            any::glue
            any::htmltools
            any::rmarkdown
 
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Import data
        env: 
          SECRET_USR: ${{ secrets.SECRET_USR }}
          SECRET_PWD: ${{ secrets.SECRET_PWD }}
        run: Rscript -e 'rmarkdown::render(input = "podMonitor.rmd")'

      - name: Rename file 
        run: mv podMonitor.html ./site/index.html
        
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add site
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
